plugins {
    id 'com.android.application'
}

android {
    namespace 'com.trueshine.pokertracker'
    compileSdk 35

    defaultConfig {
        applicationId "com.trueshine.pokertracker"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file("../keystore/pokertracker.jks")
            storePassword "pokertracker"
            keyAlias "pokertracker"
            keyPassword "pokertracker"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
